### PR TITLE
Add support from symfony 3

### PR DESCRIPTION
**Pull request by UgoSansH**
The reserved indicator "@" cannot start a plain scalar. Need Quote.

### CODE REVIEW

**Comment by gbouyge** [comment]
:+1:

**Comment by mojoLyon** [comment]
:metal:

**Comment by mikaelrandy** [comment]
:+1:

**Comment by UgoSansH** [comment]
@mikaelrandy ready to merge

**Comment by mikaelrandy** [comment]
v2.0.1

**Pull request merged**
