### PR TITLE
Add options to always check query parameters

### PR DESCRIPTION
**Pull request by t-geindre**
This PR add an option to check extra parameters for all actions. It also makes the HTTP status code of the thrown exception configurable.

### CODE REVIEW

**Comment by cedvan** [comment]
:+1:

**Comment by t-geindre** [comment]
\o/ Segfault on PHP7

**Comment by jdlabails** [comment]
:+1: 
si je comprend bien, il y aura juste à faire une ou deux lignes de config dans l'api et le middleware pour avoir ca car on aurait pas d'annotations à mettre dans les controllers ?
PS : une description aurait été bienvenue ;)

**Comment by mikaelrandy** [comment]
I agree with @jdlabails : it miss a description.

Dont forget it's a public bundle

**Comment by t-geindre** [comment]
@mikaelrandy @jdlabails New configuration options are described [here](https://github.com/M6Web/FOSRestExtraBundle/tree/feature/check-all-request-parameters#configuration). What would you add?

@jdlabails tag ?

**Comment by jdlabails** [comment]
mea culpa, I didn't see it is a public bundle
@t-geindre  just a description for the PR, no tag needed

**Comment by t-geindre** [comment]
@jdlabails done

**Comment by t-geindre** [comment]
[v1.1.0](https://github.com/M6Web/FOSRestExtraBundle/releases/tag/v1.1.0)

**Pull request merged**
