### PR TITLE
Add strict option + config refactoring

### LINKED ISSUE #4: Paramfetcher listener configuration + all strict option
The bundle configuration should define the default behavior of the `ParamFetcher` listener. So, if the option to enable extra parameters check is true, the listener has to check parameters except if current action has an annotation `@RestrictParameters(false)`.

I think the configuration organization I made in #3 would be better like this:
```yml
m6_web_fos_rest_extra:
    param_fetcher:
        allow_extra: false
        error_status_code: 400
```

As I didn't find any option to define all query parameters as strict, I also need a new feature here to make all parameters strict. Sometning like this :

```yml
m6_web_fos_rest_extra:
    param_fetcher:
        strict: true
```

Of course, because the configuration wouldn't be backward compatible with the configuration introduced in #3, all these modifications require a new major version.

### PR DESCRIPTION
**Pull request by t-geindre**
close #4 
* Add an option to define all query parameters as strict.
* Config refactoring.

New configuration example :
```yml
m6_web_fos_rest_extra:
    param_fetcher:
        allow_extra: false
        strict: true
        error_status_code: 400
```

### CODE REVIEW

**Comment by t-geindre** [comment]
doc update incoming...

**Comment by jibe84** [comment]
:+1:

**Comment by omansour** [comment]
:+1: 

bc break

**Comment by t-geindre** [comment]
[v2.0.0](https://github.com/M6Web/FOSRestExtraBundle/releases/tag/v2.0.0)

**Pull request merged**
